package com.bk.olympia.constant;

public enum ContentType {
    CHAT,
    STATUS,

    USER_ID,
    USERNAME,
    PASSWORD,
    NAME,
    GENDER,
    BALANCE,

    HISTORY_ROOM_ID,
    HISTORY_CREATED_AT,
    HISTORY_OPPONENT,
    HISTORY_ENDED_AT,
    HISTORY_RESULT_TYPE,
    HISTORY_BALANCE_CHANGED,

    REPLY,
    LOBBY_ID,
    LOBBY_NAME,
    LOBBY_PARTICIPANT,
    BET_VALUE,
    READY,

    ROOM_ID,
    TOPIC_ID,
    TOPIC_NAME,
    TOPIC_DESCRIPTION,
    IS_TOPIC_CHOSEN,
    QUESTION_ID,
    QUESTION,
    ANSWER,
    CORRECT_ANSWER_POSITION,
    DIFFICULTY,
    MONEY_PLACED,
    WINNER
}
