package com.bk.olympia.constant;

public enum ErrorType {
    AUTHENTICATION,
    DUPLICATE_USERNAME,
    PASSWORD_IS_NULL,
    NAME_IS_NULL,
    DUPLICATE_NAME,
    WRONG_NAME,
    INSUFFICIENT_BALANCE,
    TARGET_INSUFFICIENT_BALANCE,
    INVALID_INVITE,
    INVALID_ACTION,
    ANSWER_PLACING_VIOLATION
}
