spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olympia
    username: root
    password: 12345678
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db-changelog.xml
    drop-first: false
  jpa:
    open-in-view: false
server:
  port: 8109
logging:
  level:
    org:
      hibernate:
        SQL: debug
security:
  enabled: false