package com.bk.olympia.type;

public enum ErrorType {
    CONNECTION_ERROR,
    AUTHENTICATION,
    USERNAME_ALREADY_TAKEN,
    PASSWORD_IS_NULL,
    NAME_IS_NULL,
    WRONG_ID,
    INSUFFICIENT_BALANCE,
    TARGET_INSUFFICIENT_BALANCE,
    INVALID_INVITE,
    INVALID_ACTION
}
